version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-splitter-backend
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp:/tmp  # For temporary file processing
    networks:
      - pdf-splitter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdf-splitter-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pdf-splitter-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  pdf-splitter-network:
    driver: bridge

volumes:
  pdf-temp-storage:
    driver: local